<a href="https://colab.research.google.com/github/Askhilari/pythonworkbooks/blob/main/NNBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%pip install nnfs

In [ ]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

In [ ]:
class Layer_Dense:
  def __init__(self, n_inputs, n_neurons):
    self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
    self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.output = np.maximum(0, inputs)

In [ ]:
class Activation_Softmax:
  def forward(self, inputs):
    exp_values = np.exp(inputs - np.max(inputs, axis=1, keepdims=True))
    probabilities = exp_values / np.sum(exp_values, axis=1, keepdims=True)
    self.output = probabilities

In [ ]:
X, y = spiral_data(samples=100, classes=3)

In [ ]:
dense1 = Layer_Dense(2,3)
activation1 = Activation_ReLU()
dense2 = Layer_Dense(3,3)
activation2 = Activation_Softmax()

In [ ]:
dense1.forward(X)
activation1.forward(dense1.output)
dense2.forward(activation1.output)
activation2.forward(dense2.output)
print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33331734 0.3333183  0.33336434]
 [0.3332888  0.33329153 0.33341965]
 [0.33325943 0.33326396 0.33347666]
 [0.33323312 0.33323926 0.33352762]]


In [ ]:
layer1 = Layer_Dense(2, 5)
activation1 = Activation_ReLU()

In [ ]:
layer1.forward(X)
activation1.forward(layer1.output)
print(activation1.output)

[[0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 5.09662132e-05 2.82163121e-04
  0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.32260774e-03
  0.00000000e+00]
 ...
 [0.00000000e+00 6.04835898e-03 1.49472691e-02 0.00000000e+00
  1.00327469e-01]
 [0.00000000e+00 2.11660620e-02 1.17370244e-02 0.00000000e+00
  1.14487566e-01]
 [0.00000000e+00 2.21287063e-03 1.57508273e-02 0.00000000e+00
  9.66713205e-02]]


In [ ]:
#import math
#import numpy as np
#layer_outputs = [[4.8, 1.21, 2.385],
#                 [8.9, -1.81, 0.2],
#                 [1.41, 1.051, 0.026]]
#exp_values = np.exp(layer_outputs)
#norm_values = exp_values / np.sum(exp_values, axis=1, keepdims=True)
#print(norm_values)
#print(sum(norm_values))

[[8.95282664e-01 2.47083068e-02 8.00090293e-02]
 [9.99811129e-01 2.23163963e-05 1.66554348e-04]
 [5.13097164e-01 3.58333899e-01 1.28568936e-01]]
